# Generated by Django 3.2.9 on 2023-06-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcf', '0002_auto_20230613_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='vcarf_file_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
