# Generated by Django 3.2.9 on 2023-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcf', '0005_remove_userinformation_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='links',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='first_name',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='last_name',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
